### PR TITLE
fix(api): validate project id in create test run api

### LINKED ISSUE #84: When I send in a test result with a project id that does not correspond to a real project, I get a 500 error. Validate the project id and give a more meaningful message.
I was using an old Project ID and sent in some data. The error I got was 
```
  [FAILED] Unable to push report to Fern client: Response status code: 500, Response: {"error":"failed to create test run: failed to create test run: ERROR: insert or update on table \"test_runs\" violates foreign key constraint \"fk_test_runs_project_id\" (SQLSTATE 23503)"}
  Expected
      <*errors.errorString | 0x1400088b090>: 
      client: Response status code: 500, Response: {"error":"failed to create test run: failed to create test run: ERROR: insert or update on table \"test_runs\" violates foreign key constraint \"fk_test_runs_project_id\" (SQLSTATE 23503)"}
      {
          s: "client: Response status code: 500, Response: {\"error\":\"failed to create test run: failed to create test run: ERROR: insert or update on table \\\"test_runs\\\" violates foreign key constraint \\\"fk_test_runs_project_id\\\" (SQLSTATE 23503)\"}",
      }
  to be nil
  In [ReportAfterSuite] at:...
```
Please validate the Project ID - or intercept that message and convert to a more meaningful one.

### PR DESCRIPTION
**Pull request by Naganathan05**
## Description
Fixes #84. This pull request adds validation to ensure that a test run cannot be created for a non-existent project. It updates the `TestRunHandler` to check the existence of the referenced project before proceeding, and enhances the related tests to cover this scenario.

## Type of Change
- [x] Bug fix
- [ ] New feature
- [ ] Documentation update
- [ ] Refactoring
- [ ] Performance improvement

## Testing
- [x] Unit tests added/updated
- [ ] Acceptance tests added/updated
- [x] Manual testing completed

## Checklist
- [x] Code follows style guidelines
- [x] Self-review completed
- [ ] Documentation updated
- [x] Tests pass locally

---
## Summary by cubic
Validate project ID when creating a test run. Unknown projects now return 404 to prevent orphaned runs and align REST and GraphQL error handling.

- **Bug Fixes**
  - Injected `ProjectService` into `TestRunHandler` via `DomainHandlerV2`; `createTestRun` validates the project and returns 404 "Invalid project ID" (or 500 on lookup errors).
  - Added `ErrProjectNotFound`; GORM repo returns it and `ProjectService` propagates it across Get/Update/Delete/Activate/Deactivate/GrantPermission/GetOrCreate. REST `ProjectHandler` returns 404 for missing projects and 500 on other errors; GraphQL project and Jira resolvers now propagate not-found instead of wrapping.
  - Expanded tests: create test run not-found/duplicate/error paths with `internal/testhelpers`; added REST project handler 404 vs 500 cases; validated GORM repo and service behavior for not-found and wrapped errors.

<sup>Written for commit f417815c91623df22941e11fc95cc5c2ba148c24. Summary will update on new commits.</sup>

### CODE REVIEW

File: internal/api/domain_handler_v2.go [hunk 1]
```diff
@@ -43,12 +43,12 @@ func NewDomainHandlerV2(
...
 ) *DomainHandlerV2 {
 	baseHandler := NewBaseHandler(logger)
-	testRunHandler := NewTestRunHandler(testingService, logger)
+	testRunHandler := NewTestRunHandler(testingService, projectService, logger)
 	testRunHandler.SetTagService(tagService)
 	return &DomainHandlerV2{
 		authHandler:           NewAuthHandler(authMiddleware, logger),
 		healthHandler:         NewHealthHandler(logger),
-		testRunHandler:        testRunHandler,
+		testRunHandler:        NewTestRunHandler(testingService, projectService, logger),
```
Comment (bsekar) [inline internal/api/domain_handler_v2.go]: why do we need to initialize again? Line 46 does the same thing. Can we not do `testRunHandler: testRunHandler`?

**Review by bsekar — DISMISSED** [review]

**Review by bsekar — APPROVED** [review]
